### PR TITLE
CUDA 9 sync primitives and Clang support for V1.1.

### PR DESCRIPTION
**Pull request by neoblizz**

### CODE REVIEW

**Comment by neoblizz** [comment]
@sdalton1 let me know if anything else needs editing. This pull request also includes the clang support/fix.

**Comment by seanbaxter** [comment]
Hi. There are conflicts if trying to apply to master. Do you want to apply to master (moderngpu 2.0) or the 1.1 branch? If you want the 1.1 branch, could you resubmit the pull request for that target?

**Comment by neoblizz** [comment]
@seanbaxter Hi Sean, the V1.1 in moderngpu repo is set as a tag, not a branch, I might be incorrect but I don't think I can open a pull request to a tag. In the pull request, I did make sure that my commit was a child commit to V1.1. One option is to use git rebase and insert the commit after d23a7ef, unless there is a better way? I have attached a screenshot of what I see, there is no button to open a new pull request for the tag V1.1.

screen shot 2017-07-20 at 1 09 52 pm

**Comment by seanbaxter** [comment]
Ok. Sorry for being so dense there. I merged your changes into a new branch called branch_1.1. Should be easier to use this going forward.

**Comment by neoblizz** [comment]
Thank you!

**Pull request closed without merging**
